FROM ubuntu:22.04

# this dockerfile is intended for ci actions

RUN apt update && apt install -y \
  clang \
  gcc \
  scons

# copy the source code
COPY . /src

# change working directory
WORKDIR /src
